"""
comparator_oracle.py — Grover string matching with a real in-circuit comparator.

WHY THIS REPLACES THE STARTER ORACLE
------------------------------------
`grover_string_match_starter.ipynb` builds its oracle from `match_positions`,
which is computed classically beforehand:

    match_positions = [i for i in range(...) if text[i:i+len(pattern)] == pattern]
    oracle = build_marked_state_oracle(n_qubits, match_positions)

That circuit does not search. It is handed the answer and then flips the phase
of that answer. It is a correct demonstration of Grover *amplification*, but it
is not a string-matching algorithm, and it cannot support any claim about search
complexity. Any reviewer will spot this immediately.

The oracle here is given only the TEXT and the PATTERN. It computes the
comparison inside the circuit, in superposition over all candidate positions.

CONSTRUCTION
------------
Registers:
    pos  (n qubits)      candidate start position i, in superposition
    win  (M*b qubits)    the M characters of text starting at position i

Stages:
    1. WINDOW    For each concrete position i, multi-controlled writes load the
                 actual bits of text[i:i+M] into `win`, controlled on pos == i.
                 After this, |i>|0> -> |i>|text[i:i+M]>, entangled.
    2. XOR       Apply X to win[j] wherever pattern bit j is 1. Now win holds
                 window XOR pattern, which is all-zeros exactly when the window
                 equals the pattern.
    3. MARK      Flip the phase iff win is all-zeros (X-sandwich + multi-
                 controlled phase).
    4. UNCOMPUTE Reverse stages 2 and 1. This disentangles `win` from `pos` and
                 returns it to |0>, leaving the phase attached to `pos` alone.
                 Without this step the diffusion operator does not amplify
                 correctly, because the position register stays entangled with
                 window garbage.

HONEST COMPLEXITY CAVEAT (belongs in the final report)
------------------------------------------------------
Grover gives O(sqrt(N)) *queries*. But stage 1 writes the text into the circuit
with a number of gates that grows linearly in N, because each candidate position
needs its own controlled load. So for searching unstructured classical text that
we must load ourselves, total gate cost is O(N) and the quadratic query advantage
does not translate into an end-to-end speedup. The speedup is real only when the
text is already available as a quantum oracle / QRAM, or when the "text" is
generated by a function rather than stored. We measure and report this directly
rather than quoting sqrt(N) unqualified — see `scaling_table()`.

Verification is staged, mirroring how the FRQI/NEQR notebook was verified:
    check_windowing()  -> does stage 1 load the right bits?
    check_phase()      -> does the oracle flip exactly the matching positions?
    grover_search()    -> does the full algorithm return a true match?
"""

import numpy as np
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile
from qiskit.circuit.library import XGate
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator


# --------------------------------------------------------------------------
# Alphabet encoding
# --------------------------------------------------------------------------

class Alphabet:
    """Maps characters to fixed-width bit codes.

    Codes start at 1, never 0. Reason: candidate positions in the position
    register that are out of range (when N-M+1 is not a power of two) leave the
    window register at all-zeros. If any character encoded to all-zeros, those
    invalid positions could be marked as spurious matches. Starting at 1
    removes that failure mode entirely.
    """

    def __init__(self, symbols):
        # dict.fromkeys removes duplicates while preserving first-seen order,
        # so Alphabet("AABC") and Alphabet("ABC") produce identical encodings.
        # Order stability matters: the codes end up baked into circuits, and a
        # reordered alphabet would silently change every gate.
        symbols = list(dict.fromkeys(symbols))
        self.symbols = symbols

        # Width in bits. The "+ 1" reserves code 0 as unused (see class
        # docstring), so an N-symbol alphabet must address N+1 values.
        # 4 symbols -> codes 1..4 -> needs 3 bits, not 2.
        self.bits = max(1, int(np.ceil(np.log2(len(symbols) + 1))))

        # code:   character -> integer, starting at 1
        # decode: integer -> character, for reading measurement results back
        self.code = {s: i + 1 for i, s in enumerate(symbols)}
        self.decode = {v: k for k, v in self.code.items()}

        if len(symbols) + 1 > 2 ** self.bits:
            raise ValueError("alphabet too large for {} bits".format(self.bits))

    def to_bits(self, ch):
        """Character -> list of bits, MSB first.

        MSB-first ordering is a convention chosen once and then relied on
        everywhere: window loading, pattern XOR, and measurement decoding all
        assume it. Flipping it would still "work" in the sense that matches
        would be found, because both sides of the comparison would flip
        together -- but decoded characters would come out scrambled.
        """
        return [int(b) for b in format(self.code[ch], "0{}b".format(self.bits))]

    def __len__(self):
        return len(self.symbols)

    def __repr__(self):
        return "Alphabet({} symbols, {} bits/char)".format(len(self.symbols), self.bits)


# --------------------------------------------------------------------------
# Oracle construction
# --------------------------------------------------------------------------

def build_comparator_oracle(text, pattern, alphabet, n_pos=None):
    """Return (oracle circuit, n_pos, n_win) for marking positions where
    text[i:i+M] == pattern. The oracle never receives the match positions."""
    N, M = len(text), len(pattern)

    # Candidate start positions: a pattern of length M can begin anywhere from
    # index 0 up to N-M inclusive, so N-M+1 possibilities.
    n_cand = N - M + 1
    if n_cand < 1:
        raise ValueError("pattern longer than text")

    # Position register width. Note this rounds UP to a power of two, so when
    # n_cand is not itself a power of two the register addresses more states
    # than there are valid positions. Those extra states are unreachable
    # padding -- they never trigger a controlled load, so their window stays
    # at all-zeros. This is exactly why alphabet codes start at 1: if any
    # character encoded to zero, the padding would look like a match.
    if n_pos is None:
        n_pos = max(1, int(np.ceil(np.log2(n_cand))))

    b = alphabet.bits
    n_win = M * b          # M characters, b bits each, laid out end to end

    # Two registers, no ancillas. The window register doubles as the comparison
    # workspace and as the target of the phase flip, which is what keeps the
    # qubit count down.
    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(n_win, "win")
    qc = QuantumCircuit(pos, win, name="comparator_oracle")

    # ---- Stage 1: window loading -----------------------------------------
    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)

    # ---- Stage 2: XOR the pattern in --------------------------------------
    # The pattern is CLASSICAL and known at circuit-build time, so XOR-ing it in
    # needs no controls at all -- just an X on each bit position where the
    # pattern has a 1. Applying X to a qubit flips it, and flipping window bit j
    # exactly when pattern bit j is 1 computes (window XOR pattern) in place.
    #
    # The point of the XOR: after it, the window register is all-zeros if and
    # only if the window equalled the pattern. That converts "are these two
    # strings equal?" into "is this register all zeros?", which is a condition a
    # single multi-controlled gate can test.
    pattern_bits = [bit for ch in pattern for bit in alphabet.to_bits(ch)]
    for j, bit in enumerate(pattern_bits):
        if bit == 1:
            qc.x(win[j])

    # ---- Stage 3: phase-flip when win is all zeros ------------------------
    # Multi-controlled gates trigger on all-ONES, but we need to detect
    # all-ZEROS. The standard trick is to sandwich the gate between layers of X:
    # flip everything, so all-zeros becomes all-ones, test it, then flip back.
    qc.x(win)
    if n_win == 1:
        # A one-qubit "multi-controlled phase" has no controls left -- it is
        # just Z, which applies the -1 phase to |1>.
        qc.z(win[0])
    else:
        # mcp(pi, controls, target) applies phase e^{i*pi} = -1 when every
        # control AND the target are |1>. The choice of which qubit acts as
        # "target" is arbitrary: the phase is global to that basis state, so
        # any partition of the register into controls plus one target gives the
        # same operator.
        qc.mcp(np.pi, [win[k] for k in range(n_win - 1)], win[n_win - 1])
    qc.x(win)

    # ---- Stage 4: uncompute ----------------------------------------------
    # Reverse stages 2 and 1, in that order. Both are built purely from X and
    # multi-controlled X gates, each of which is its own inverse, so "reversing"
    # means simply applying the same operations again.
    #
    # Why this is mandatory rather than tidy: after stage 1 the window register
    # is ENTANGLED with the position register (|i> is paired with the text at
    # position i). The phase flip from stage 3 is attached to that joint state.
    # If we stopped here and applied the diffusion operator to `pos` alone, the
    # window would act as a which-path record -- the amplitudes could not
    # interfere, and Grover would not amplify anything.
    #
    # Uncomputing returns the window to |0> for every branch, disentangling it.
    # The phase then belongs to `pos` alone and interference works.
    # check_phase() measures the leftover entanglement as "leakage"; it should
    # be exactly 0.
    for j, bit in enumerate(pattern_bits):
        if bit == 1:
            qc.x(win[j])
    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)  # self-inverse

    return qc, n_pos, n_win


def _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand):
    """|i>|w>  ->  |i>|w XOR text[i:i+M]>.

    Built only from multi-controlled X gates, so it is its own inverse — the
    same routine serves as both the compute and uncompute step.
    """
    b = alphabet.bits

    # One pass per candidate position. This loop is the whole reason the oracle
    # costs O(N) gates rather than O(1): the text is classical data that has to
    # be written into the circuit, position by position. It is the source of the
    # measured 1.39 scaling exponent, and the reason Grover's sqrt(N) query
    # advantage does not survive here.
    for i in range(n_cand):
        # The M characters starting at position i, flattened to a bit list.
        # This is evaluated in PYTHON at build time -- which is fine, and is not
        # the same as precomputing the answer. We are writing the text into the
        # circuit, not comparing it. The comparison happens in superposition,
        # later, in stage 2/3.
        window_bits = [bit for ch in text[i:i + M] for bit in alphabet.to_bits(ch)]

        for j, bit in enumerate(window_bits):
            if bit == 1:
                # Write a 1 into window bit j, but only on the branch where the
                # position register holds i.
                #
                # ctrl_state=i makes the gate fire on the basis state |i>
                # instead of the default all-ones. Qiskit reads ctrl_state
                # little-endian across the control list, which matches pos[0]
                # being the least significant bit -- so passing the integer i
                # directly is correct with no bit reversal.
                #
                # Bits that are 0 need no gate: the window starts at |0>, so
                # "write a 0" is a no-op. That halves the gate count on average.
                qc.append(XGate().control(n_pos, ctrl_state=i),
                          list(pos) + [win[j]])


def build_diffusion(n_qubits):
    """Grover diffusion operator: reflection about the uniform superposition."""
    qc = QuantumCircuit(n_qubits, name="diffusion")

    # The diffusion operator is 2|s><s| - I, a reflection about the uniform
    # superposition |s>. It is built by mapping |s> to |0...0>, reflecting about
    # |0...0>, then mapping back:
    #
    #   H layer  : |s> -> |0...0>            (undoes the initial superposition)
    #   X layer  : |0...0> -> |1...1>        (so a multi-controlled gate can see it)
    #   MCZ      : flip the phase of |1...1> (the reflection itself)
    #   X layer  : undo
    #   H layer  : undo
    #
    # Combined with the oracle's reflection about the marked states, each
    # oracle+diffusion pair rotates the state vector toward the answer by a
    # fixed angle -- which is why the iteration count is a fixed optimum rather
    # than "more is better", and why over-rotation is possible.
    qc.h(range(n_qubits))
    qc.x(range(n_qubits))
    if n_qubits == 1:
        qc.z(0)
    else:
        qc.mcp(np.pi, list(range(n_qubits - 1)), n_qubits - 1)
    qc.x(range(n_qubits))
    qc.h(range(n_qubits))
    return qc


# --------------------------------------------------------------------------
# Staged verification
# --------------------------------------------------------------------------

def check_windowing(text, pattern, alphabet, probe_position, shots=2048):
    """Stage 1 check: with pos prepared in the basis state |probe_position>,
    the window register must hold exactly text[probe:probe+M]."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    n_pos = max(1, int(np.ceil(np.log2(n_cand))))
    b = alphabet.bits

    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(M * b, "win")
    cr = ClassicalRegister(M * b, "c")
    qc = QuantumCircuit(pos, win, cr)

    for k in range(n_pos):                      # prepare |probe_position>
        if (probe_position >> k) & 1:
            qc.x(pos[k])

    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)
    qc.measure(win, cr)

    sim = AerSimulator()
    counts = sim.run(transpile(qc, sim), shots=shots).result().get_counts()
    observed = max(counts, key=counts.get)[::-1]   # reverse to win[0]-first

    chars = []
    for c in range(M):
        code = int(observed[c * b:(c + 1) * b], 2)
        chars.append(alphabet.decode.get(code, "?"))
    recovered = "".join(chars)
    expected = text[probe_position:probe_position + M]
    return recovered, expected, recovered == expected


def check_phase(text, pattern, alphabet):
    """Stage 2 check: apply the oracle to a uniform superposition and inspect
    amplitude signs. Exactly the true match positions should be negative.

    Uses the statevector directly, so this is exact — no shot noise, and it
    also confirms uncomputation worked (win must return to |0>, otherwise the
    position amplitudes would not be cleanly separable)."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)

    qc = QuantumCircuit(n_pos + n_win)
    qc.h(range(n_pos))
    qc.compose(oracle, inplace=True)

    sv = Statevector(qc).data
    truth = [i for i in range(n_cand) if text[i:i + M] == pattern]

    flipped, leaked = [], 0.0
    for i in range(2 ** n_pos):
        amp = sv[i]                       # win == 0 block: index == pos value
        if amp.real < -1e-9:
            flipped.append(i)
    # any amplitude outside the win==0 block means uncomputation failed
    for idx in range(len(sv)):
        if idx >= 2 ** n_pos and abs(sv[idx]) > 1e-9:
            leaked += abs(sv[idx]) ** 2

    return sorted(flipped), truth, sorted(flipped) == truth, leaked


def grover_search(text, pattern, alphabet, iterations=None, shots=2048,
                  return_circuit=False):
    """Full Grover search. Returns (best_position, counts, n_iterations)."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)
    diffusion = build_diffusion(n_pos)

    n_matches = max(1, sum(1 for i in range(n_cand)
                           if text[i:i + M] == pattern))
    if iterations is None:
        # Standard optimal count. Note this assumes the number of matches is
        # known; with an unknown count the BBHT exponential-schedule variant
        # applies, at the cost of a constant factor.
        iterations = max(1, int(np.floor(np.pi / 4 * np.sqrt(2 ** n_pos / n_matches))))

    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(n_win, "win")
    cr = ClassicalRegister(n_pos, "c")
    qc = QuantumCircuit(pos, win, cr)
    qc.h(pos)
    for _ in range(iterations):
        qc.compose(oracle, qubits=list(pos) + list(win), inplace=True)
        qc.compose(diffusion, qubits=list(pos), inplace=True)
    qc.measure(pos, cr)

    sim = AerSimulator()
    counts = sim.run(transpile(qc, sim), shots=shots).result().get_counts()
    best = int(max(counts, key=counts.get), 2)
    if return_circuit:
        return best, counts, iterations, qc
    return best, counts, iterations


# --------------------------------------------------------------------------
# Resource scaling — feeds the benchmarking section of the report
# --------------------------------------------------------------------------

def oracle_resources(text, pattern, alphabet):
    """Transpiled qubit count, depth and CX count for one oracle call."""
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)
    # No backend here on purpose: we want the abstract gate cost, not a cost
    # capped by whatever the local simulator can hold. Counting must keep
    # working past the ~27-qubit simulation ceiling.
    t = transpile(oracle, basis_gates=["u", "cx"], optimization_level=1)
    ops = t.count_ops()
    return {
        "n_text": len(text),
        "n_pattern": len(pattern),
        "alphabet_bits": alphabet.bits,
        "qubits": n_pos + n_win,
        "pos_qubits": n_pos,
        "win_qubits": n_win,
        "depth": t.depth(),
        "cx": ops.get("cx", 0),
        "total_gates": sum(ops.values()),
    }


def scaling_table(alphabet, pattern, text_lengths, base_text):
    """Resource cost as text length grows — the evidence for the O(N)
    data-loading caveat described in the module docstring."""
    rows = []
    for N in text_lengths:
        t = (base_text * ((N // len(base_text)) + 1))[:N]
        # guarantee at least one match so the instance is non-degenerate
        t = t[:-len(pattern)] + pattern if len(t) > len(pattern) else t
        rows.append(oracle_resources(t, pattern, alphabet))
    return rows


if __name__ == "__main__":
    alpha = Alphabet("ABXY")
    text, pattern = "ABABXYAB", "XY"
    print(alpha, "\n")

    rec, exp, ok = check_windowing(text, pattern, alpha, probe_position=4)
    print("[1] windowing @pos4: got {!r} expected {!r} -> {}".format(rec, exp, ok))

    flipped, truth, ok, leak = check_phase(text, pattern, alpha)
    print("[2] phase-flipped {} truth {} -> {} (leakage {:.2e})".format(
        flipped, truth, ok, leak))

    best, counts, iters = grover_search(text, pattern, alpha)
    top = sorted(counts.items(), key=lambda kv: -kv[1])[:3]
    print("[3] grover({} iters) best={} truth={} -> {}".format(
        iters, best, truth, best in truth))
    print("    top counts:", top)

    print("\n[4] resources:", oracle_resources(text, pattern, alpha))
