"""
comparator_oracle.py — Grover string matching with a real in-circuit comparator.

WHY THIS REPLACES THE STARTER ORACLE
------------------------------------
`grover_string_match_starter.ipynb` builds its oracle from `match_positions`,
which is computed classically beforehand:

    match_positions = [i for i in range(...) if text[i:i+len(pattern)] == pattern]
    oracle = build_marked_state_oracle(n_qubits, match_positions)

That circuit does not search. It is handed the answer and then flips the phase
of that answer. It is a correct demonstration of Grover *amplification*, but it
is not a string-matching algorithm, and it cannot support any claim about search
complexity. Any reviewer will spot this immediately.

The oracle here is given only the TEXT and the PATTERN. It computes the
comparison inside the circuit, in superposition over all candidate positions.

CONSTRUCTION
------------
Registers:
    pos  (n qubits)      candidate start position i, in superposition
    win  (M*b qubits)    the M characters of text starting at position i

Stages:
    1. WINDOW    For each concrete position i, multi-controlled writes load the
                 actual bits of text[i:i+M] into `win`, controlled on pos == i.
                 After this, |i>|0> -> |i>|text[i:i+M]>, entangled.
    2. XOR       Apply X to win[j] wherever pattern bit j is 1. Now win holds
                 window XOR pattern, which is all-zeros exactly when the window
                 equals the pattern.
    3. MARK      Flip the phase iff win is all-zeros (X-sandwich + multi-
                 controlled phase).
    4. UNCOMPUTE Reverse stages 2 and 1. This disentangles `win` from `pos` and
                 returns it to |0>, leaving the phase attached to `pos` alone.
                 Without this step the diffusion operator does not amplify
                 correctly, because the position register stays entangled with
                 window garbage.

HONEST COMPLEXITY CAVEAT (belongs in the final report)
------------------------------------------------------
Grover gives O(sqrt(N)) *queries*. But stage 1 writes the text into the circuit
with a number of gates that grows linearly in N, because each candidate position
needs its own controlled load. So for searching unstructured classical text that
we must load ourselves, total gate cost is O(N) and the quadratic query advantage
does not translate into an end-to-end speedup. The speedup is real only when the
text is already available as a quantum oracle / QRAM, or when the "text" is
generated by a function rather than stored. We measure and report this directly
rather than quoting sqrt(N) unqualified — see `scaling_table()`.

Verification is staged, mirroring how the FRQI/NEQR notebook was verified:
    check_windowing()  -> does stage 1 load the right bits?
    check_phase()      -> does the oracle flip exactly the matching positions?
    grover_search()    -> does the full algorithm return a true match?
"""

import numpy as np
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, transpile
from qiskit.circuit.library import XGate
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator


# --------------------------------------------------------------------------
# Alphabet encoding
# --------------------------------------------------------------------------

class Alphabet:
    """Maps characters to fixed-width bit codes.

    Codes start at 1, never 0. Reason: candidate positions in the position
    register that are out of range (when N-M+1 is not a power of two) leave the
    window register at all-zeros. If any character encoded to all-zeros, those
    invalid positions could be marked as spurious matches. Starting at 1
    removes that failure mode entirely.
    """

    def __init__(self, symbols):
        symbols = list(dict.fromkeys(symbols))  # dedupe, preserve order
        self.symbols = symbols
        self.bits = max(1, int(np.ceil(np.log2(len(symbols) + 1))))
        self.code = {s: i + 1 for i, s in enumerate(symbols)}
        self.decode = {v: k for k, v in self.code.items()}
        if len(symbols) + 1 > 2 ** self.bits:
            raise ValueError("alphabet too large for {} bits".format(self.bits))

    def to_bits(self, ch):
        """Character -> list of bits, MSB first."""
        return [int(b) for b in format(self.code[ch], "0{}b".format(self.bits))]

    def __len__(self):
        return len(self.symbols)

    def __repr__(self):
        return "Alphabet({} symbols, {} bits/char)".format(len(self.symbols), self.bits)


# --------------------------------------------------------------------------
# Oracle construction
# --------------------------------------------------------------------------

def build_comparator_oracle(text, pattern, alphabet, n_pos=None):
    """Return (oracle circuit, n_pos, n_win) for marking positions where
    text[i:i+M] == pattern. The oracle never receives the match positions."""
    N, M = len(text), len(pattern)
    n_cand = N - M + 1
    if n_cand < 1:
        raise ValueError("pattern longer than text")
    if n_pos is None:
        n_pos = max(1, int(np.ceil(np.log2(n_cand))))

    b = alphabet.bits
    n_win = M * b

    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(n_win, "win")
    qc = QuantumCircuit(pos, win, name="comparator_oracle")

    # ---- Stage 1: window loading -----------------------------------------
    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)

    # ---- Stage 2: XOR the pattern in --------------------------------------
    pattern_bits = [bit for ch in pattern for bit in alphabet.to_bits(ch)]
    for j, bit in enumerate(pattern_bits):
        if bit == 1:
            qc.x(win[j])

    # ---- Stage 3: phase-flip when win is all zeros ------------------------
    qc.x(win)
    if n_win == 1:
        qc.z(win[0])
    else:
        qc.mcp(np.pi, [win[k] for k in range(n_win - 1)], win[n_win - 1])
    qc.x(win)

    # ---- Stage 4: uncompute ----------------------------------------------
    for j, bit in enumerate(pattern_bits):
        if bit == 1:
            qc.x(win[j])
    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)  # self-inverse

    return qc, n_pos, n_win


def _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand):
    """|i>|w>  ->  |i>|w XOR text[i:i+M]>.

    Built only from multi-controlled X gates, so it is its own inverse — the
    same routine serves as both the compute and uncompute step.
    """
    b = alphabet.bits
    for i in range(n_cand):
        window_bits = [bit for ch in text[i:i + M] for bit in alphabet.to_bits(ch)]
        # ctrl_state selects the basis state pos == i. Qiskit reads ctrl_state
        # little-endian across the control list, matching pos[0] as LSB.
        for j, bit in enumerate(window_bits):
            if bit == 1:
                qc.append(XGate().control(n_pos, ctrl_state=i),
                          list(pos) + [win[j]])


def build_diffusion(n_qubits):
    """Grover diffusion operator: reflection about the uniform superposition."""
    qc = QuantumCircuit(n_qubits, name="diffusion")
    qc.h(range(n_qubits))
    qc.x(range(n_qubits))
    if n_qubits == 1:
        qc.z(0)
    else:
        qc.mcp(np.pi, list(range(n_qubits - 1)), n_qubits - 1)
    qc.x(range(n_qubits))
    qc.h(range(n_qubits))
    return qc


# --------------------------------------------------------------------------
# Staged verification
# --------------------------------------------------------------------------

def check_windowing(text, pattern, alphabet, probe_position, shots=2048):
    """Stage 1 check: with pos prepared in the basis state |probe_position>,
    the window register must hold exactly text[probe:probe+M]."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    n_pos = max(1, int(np.ceil(np.log2(n_cand))))
    b = alphabet.bits

    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(M * b, "win")
    cr = ClassicalRegister(M * b, "c")
    qc = QuantumCircuit(pos, win, cr)

    for k in range(n_pos):                      # prepare |probe_position>
        if (probe_position >> k) & 1:
            qc.x(pos[k])

    _load_window(qc, pos, win, text, M, alphabet, n_pos, n_cand)
    qc.measure(win, cr)

    sim = AerSimulator()
    counts = sim.run(transpile(qc, sim), shots=shots).result().get_counts()
    observed = max(counts, key=counts.get)[::-1]   # reverse to win[0]-first

    chars = []
    for c in range(M):
        code = int(observed[c * b:(c + 1) * b], 2)
        chars.append(alphabet.decode.get(code, "?"))
    recovered = "".join(chars)
    expected = text[probe_position:probe_position + M]
    return recovered, expected, recovered == expected


def check_phase(text, pattern, alphabet):
    """Stage 2 check: apply the oracle to a uniform superposition and inspect
    amplitude signs. Exactly the true match positions should be negative.

    Uses the statevector directly, so this is exact — no shot noise, and it
    also confirms uncomputation worked (win must return to |0>, otherwise the
    position amplitudes would not be cleanly separable)."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)

    qc = QuantumCircuit(n_pos + n_win)
    qc.h(range(n_pos))
    qc.compose(oracle, inplace=True)

    sv = Statevector(qc).data
    truth = [i for i in range(n_cand) if text[i:i + M] == pattern]

    flipped, leaked = [], 0.0
    for i in range(2 ** n_pos):
        amp = sv[i]                       # win == 0 block: index == pos value
        if amp.real < -1e-9:
            flipped.append(i)
    # any amplitude outside the win==0 block means uncomputation failed
    for idx in range(len(sv)):
        if idx >= 2 ** n_pos and abs(sv[idx]) > 1e-9:
            leaked += abs(sv[idx]) ** 2

    return sorted(flipped), truth, sorted(flipped) == truth, leaked


def grover_search(text, pattern, alphabet, iterations=None, shots=2048,
                  return_circuit=False):
    """Full Grover search. Returns (best_position, counts, n_iterations)."""
    M = len(pattern)
    n_cand = len(text) - M + 1
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)
    diffusion = build_diffusion(n_pos)

    n_matches = max(1, sum(1 for i in range(n_cand)
                           if text[i:i + M] == pattern))
    if iterations is None:
        # Standard optimal count. Note this assumes the number of matches is
        # known; with an unknown count the BBHT exponential-schedule variant
        # applies, at the cost of a constant factor.
        iterations = max(1, int(np.floor(np.pi / 4 * np.sqrt(2 ** n_pos / n_matches))))

    pos = QuantumRegister(n_pos, "pos")
    win = QuantumRegister(n_win, "win")
    cr = ClassicalRegister(n_pos, "c")
    qc = QuantumCircuit(pos, win, cr)
    qc.h(pos)
    for _ in range(iterations):
        qc.compose(oracle, qubits=list(pos) + list(win), inplace=True)
        qc.compose(diffusion, qubits=list(pos), inplace=True)
    qc.measure(pos, cr)

    sim = AerSimulator()
    counts = sim.run(transpile(qc, sim), shots=shots).result().get_counts()
    best = int(max(counts, key=counts.get), 2)
    if return_circuit:
        return best, counts, iterations, qc
    return best, counts, iterations


# --------------------------------------------------------------------------
# Resource scaling — feeds the benchmarking section of the report
# --------------------------------------------------------------------------

def oracle_resources(text, pattern, alphabet):
    """Transpiled qubit count, depth and CX count for one oracle call."""
    oracle, n_pos, n_win = build_comparator_oracle(text, pattern, alphabet)
    # No backend here on purpose: we want the abstract gate cost, not a cost
    # capped by whatever the local simulator can hold. Counting must keep
    # working past the ~27-qubit simulation ceiling.
    t = transpile(oracle, basis_gates=["u", "cx"], optimization_level=1)
    ops = t.count_ops()
    return {
        "n_text": len(text),
        "n_pattern": len(pattern),
        "alphabet_bits": alphabet.bits,
        "qubits": n_pos + n_win,
        "pos_qubits": n_pos,
        "win_qubits": n_win,
        "depth": t.depth(),
        "cx": ops.get("cx", 0),
        "total_gates": sum(ops.values()),
    }


def scaling_table(alphabet, pattern, text_lengths, base_text):
    """Resource cost as text length grows — the evidence for the O(N)
    data-loading caveat described in the module docstring."""
    rows = []
    for N in text_lengths:
        t = (base_text * ((N // len(base_text)) + 1))[:N]
        # guarantee at least one match so the instance is non-degenerate
        t = t[:-len(pattern)] + pattern if len(t) > len(pattern) else t
        rows.append(oracle_resources(t, pattern, alphabet))
    return rows


if __name__ == "__main__":
    alpha = Alphabet("ABXY")
    text, pattern = "ABABXYAB", "XY"
    print(alpha, "\n")

    rec, exp, ok = check_windowing(text, pattern, alpha, probe_position=4)
    print("[1] windowing @pos4: got {!r} expected {!r} -> {}".format(rec, exp, ok))

    flipped, truth, ok, leak = check_phase(text, pattern, alpha)
    print("[2] phase-flipped {} truth {} -> {} (leakage {:.2e})".format(
        flipped, truth, ok, leak))

    best, counts, iters = grover_search(text, pattern, alpha)
    top = sorted(counts.items(), key=lambda kv: -kv[1])[:3]
    print("[3] grover({} iters) best={} truth={} -> {}".format(
        iters, best, truth, best in truth))
    print("    top counts:", top)

    print("\n[4] resources:", oracle_resources(text, pattern, alpha))
